name: Sample Flow

on:
  push:
    branches:
      - 'master'

jobs:
  checkoutEcho:
    name: Test expected failure
    runs-on: ubuntu-latest
    steps:
    - name: Fake command 
      continue-on-error: true
      outputs:
        out:
          description: 'Test output'
      run: |
        lol idk
        ::set-output name=out::$?
    #- name: Test response
    #  run: test $? = 0
