name: Sample Flow

on:
  push:
    tags:
      - 'hello*'

jobs:
  checkoutEcho:
    name: Test expected failure
    runs-on: ubuntu-latest
    steps:
    - name: Fake command 
      continue-on-error: true
      run: lol idk
    - name: Test response
      run: test $? = 0
