name: Sample Flow

on:
  push:
    branches:
      - 'master'

jobs:
  checkoutEcho:
    name: Test expected failure
    runs-on: ubuntu-latest
    steps:
    - name: Fake command 
      run: lol idk
    - name: Test response
      run: exit 1
      if: failure()

